version '1'
services: 
  api: 
    build: 
      context: ./
      target: production
    container_name: some-postgres
    depends_on: 
      - db
    environment: 
      DB_HOST: db
      DB_NAME: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_USER: postgres
      NODE_ENV: production
    image: quotes-api
    links: 
      - db
    ports: 
      - "3000:3000"
    volumes: 
      - "./:/src"
  db: 
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: "postgres:14.1-alpine"
    ports: 
      - "5432:5432"
    restart: always
    volumes: 
      - "db:/var/lib/postgresql/data"
      - "./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql"
version: "3.8"
volumes: 
  db: 
    driver: local
